name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Checkout and pull branch
        run: git checkout $GIT_BRANCH && git pull

      - name: Install Packages
        run: yarn

      - name: Publish package
        run: npx lerna publish --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
