name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish package
        run: yarn && npx lerna publish --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
